project:

  name: RetailDWGen

general:

  seed: 4711

  encoding: utf-8

  delimiter: ";"

output:

  folder: output

generator:

  warengruppen: 50
  hersteller: 100
  lieferanten: 100
  kunden: 1000

  marken: 250
  filialen: 50
  artikel: 10000
  mitarbeiter: 500
  lager: 25
  organisation: 100
